[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "SIM"]
extend-ignore = ["E501"]  # Allow long docstring lines

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
