services:
  - type: web
    name: search-demo
    env: docker
    region: frankfurt
    plan: free
    autoDeploy: true
    envVars:
      - key: ELASTIC_URL
        sync: false
      - key: ELASTIC_API_KEY
        sync: false
      - key: ELASTIC_INDEX
        value: products
